[tool.ruff]
target-version = "py311"


[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # flake8-tidy-imports
    "TID",
    # flake8-pytest-style
    "PT",
    # airflow-variable-name-task-id-mismatch
    "AIR",

]

[tool.ruff.lint.pycodestyle]
ignore-overlong-task-comments = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
# Format all docstring code snippets with a line length of 60.
docstring-code-line-length = 60
